---
- hosts: k8s_cluster
  tasks:
  - name: Set maxium number of inotify file watches
    sysctl:
      name: fs.inotify.max_user_watches
      value: "{{ inotify_max_watches | string }}"
      sysctl_set: yes
      sysctl_file: "{{ sysctl_file_path }}"
      state: present
      reload: yes

  - name: Set maxium number of inotify instances
    sysctl:
      name: fs.inotify.max_user_instances
      value: "{{ inotify_max_instances | string }}"
      sysctl_set: yes
      sysctl_file: "{{ sysctl_file_path }}"
      state: present
      reload: yes