---
- hosts: all
  tasks:
    - name: Create script to solve "no PodsandBox found with Id" error
      ansible.builtin.copy:
        dest: /usr/local/bin/fix-nopodsandbox-found
        owner: root
        group: root
        mode: 0700
        content: |
          #!/bin/bash
          if systemctl is-active --quiet kubelet; then
            if journalctl -u kubelet --since "2 minute ago" | grep -F '"Failed to start ContainerManager" err="failed to build map of initial containers from runtime: no PodsandBox found with Id'; then
              systemctl stop kubelet
              crictl ps -a -q | xargs crictl stop
              crictl ps -a -q | xargs crictl rm
              systemctl start kubelet
              sleep 90
            fi
          fi

    - name: Handle cron job for "no PodsandBox found with Id" error
      ansible.builtin.cron:
        name: "fix-no-podsandbox"
        state: "{{ state | default('present') }}"
        job: "/usr/local/bin/fix-nopodsandbox-found >> /tmp/$$.log"
