---
- hosts: all
  tasks:
    - name: Create script to solve "no PodsandBox found with Id" error
      ansible.builtin.copy:
        dest: /usr/local/bin/fix-nopodsandbox-found
        owner: root
        group: root
        mode: 0700
        content: |
          #!/bin/bash
          crictl rm $(crictl ps -a | grep "$(journalctl -u kubelet --since "2 minute ago" -o cat -g 'no PodsandBox found with Id' -n1 | awk -F' ' '{print $NF}' | cut -c 2-14)"|awk '{ print $1 }')

    - name: Handle cron job for "no PodsandBox found with Id" error
      ansible.builtin.cron:
        name: "fix-no-podsandbox"
        state: "{{ state | default('present') }}"
        job: "/usr/local/bin/fix-nopodsandbox-found >> /tmp/$$.log"
