---
- hosts: all
  tasks:
    - name: Create script to solve "no PodsandBox found with Id" error
      ansible.builtin.copy:
        dest: /usr/local/bin/fix-nopodsandbox-found
        owner: root
        group: root
        mode: 0700
        content: |
          #!/bin/bash
          export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
          container_id="$(journalctl -u kubelet --since "2 minute ago" -o cat -g 'no PodsandBox found with Id' -n1 | awk -F' ' '{print $NF}' | cut -c 2-14)"
          if [[ -z "${container_id}" ]]; then
            exit 0
          else
            crictl rm $(crictl ps -a | grep "${container_id}" | awk '{ print $1 }')
          fi

    - name: Handle cron job for "no PodsandBox found with Id" error
      ansible.builtin.cron:
        name: "fix-no-podsandbox"
        state: "{{ state | default('present') }}"
        job: "/usr/local/bin/fix-nopodsandbox-found >> /tmp/$$.log"
